language: swift
before_install: 
    - export LANG=en_US.UTF-8
    - rake install
script: 
    - rake clean:example
    - rake test
    - rake analyze
rvm:
    - "2.0.0"
notifications:
    email:
        recipients:
         - joe.howard@raizlabs.com
         - matt.buckley@raizlabs.com
        on_success: always
        on_failure: always